# Insert your SSID and Your PWD after inital setup
wifi:
  ssid: "My SSID"
  password: "Wifi Password"
  reboot_timeout: 15min

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "AirGradient Fallback Hotspot"
    password: "Password123"

# Enable the captive portal for inital WiFi setup
captive_portal:

dashboard_import:
  package_import_url: github://rf152/airgradient-pro-esphome/aigradient-pro-esphome.yaml

# Creates a simple web server on the node that can be accessed through any browser
# https://esphome.io/components/web_server.html
web_server:
  port: 80
  include_internal: true


substitutions:
  name: "airgradient-pro"
  upper_name: "AirGradient Pro"
  # Pick your temperature unit:
  # temperature_units: "F"
  temperature_units: "C"

esphome:
  name: "${name}"
  platform: ESP8266
  board: d1_mini
  name_add_mac_suffix: true

  project:
    name: rf152.airgradient_pro_esphome
    version: "1.1"

  
# Enable Home Assistant API (API password is deprecated in favor of encryption key)
# https://esphome.io/components/api.html
api:
  encryption:
    key: "SecretKey"

ota:

# Enable logging
logger:

i2c:
  sda: D2
  scl: D1

font:
  - file: "fonts/ltype.ttf"
    id: helvetica
    size: 12
    glyphs: >-
      !"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyzµ³/

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    address: 0x3C
    contrast: 10%
    # invert: true
    update_interval: 5s
    lambda: |-
      it.printf(0, 0, id(helvetica), "%.1f°C", id(temp).state);
      it.printf(0, 12, id(helvetica), "%.1f%% RH", id(humidity).state);
      it.printf(0, 24, id(helvetica), "%.0fppm", id(co2).state);
      it.printf(0, 36, id(helvetica), "%.0f µg/m³", id(pm_2_5).state);

uart:
  - rx_pin: D5
    tx_pin: D6
    baud_rate: 9600
    id: uart_1

  - rx_pin: D4
    tx_pin: D3
    baud_rate: 9600
    id: uart_2

sensor:
  # https://esphome.io/components/sensor/sht3xd.html
  - platform: sht3xd
    temperature:
      id: temp
      name: Temperature
    humidity:
      id: humidity
      name: Relative Humidity
    address: 0x44
    update_interval: 10s

  # https://esphome.io/components/sensor/pmsx003.html
  - platform: pmsx003
    type: PMSX003
    uart_id: uart_1
    pm_1_0:
      id: pm_1_0
      name: "Particulate Matter <1.0µm Concentration"
    pm_2_5:
      id: pm_2_5
      name: "Particulate Matter <2.5µm Concentration"
    pm_10_0:
      id: pm_10_0
      name: "Particulate Matter <10.0µm Concentration"
    pm_0_3um:
      id: pm_0_3um
      name: "Particulate Matter >0.3µm Count"
      icon: mdi:blur
    pm_0_5um:
      id: pm_0_5um
      name: "Particulate Matter >0.5µm Count"
      icon: mdi:blur
    pm_1_0um:
      id: pm_1_0um
      name: "Particulate Matter >1.0µm Count"
      icon: mdi:blur
    pm_2_5um:
      id: pm_2_5um
      name: "Particulate Matter >2.5µm Count"
      icon: mdi:blur
    # The basic PMSX003 version doesn't have a formaldehyde sensor.
    # formaldehyde:
    #   id: hcho
    #   name: "Formaldehyde (HCHO) concentration in µg per cubic meter"
    update_interval: 3min # Sensor will go into sleep mode for extended operation lifetime

  # https://esphome.io/components/sensor/senseair.html
  - platform: senseair
    uart_id: uart_2
    co2:
      id: co2
      name: "SenseAir CO2 Value"
    update_interval: 60s

  # https://esphome.io/components/sensor/sgp4x.html
  # https://sensirion.com/products/catalog/SGP41/
  # Note that these "index" values don't have a unit. They are a scale from 1-500.
  # - platform: sgp4x
  #   voc:
  #     id: voc
  #     name: "VOC Index"
  #     icon: mdi:chemical-weapon
  #     # See https://sensirion.com/media/documents/02232963/6294E043/Info_Note_VOC_Index.pdf
  #     # 0-150 green, 151-250 yellow, 251-400 orange, 401+ red
  #   nox:
  #     id: nox
  #     name: "NOx Index"
  #     icon: mdi:chemical-weapon
  #     # See https://sensirion.com/media/documents/9F289B95/6294DFFC/Info_Note_NOx_Index.pdf
  #     # 0-19 green, 20+ yellow (see PDF for why we don't do more than this)
  #   compensation:
  #     humidity_source: humidity
  #     temperature_source: temp

  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    id: airgradient_wifi_signal
    update_interval: 60s

  - platform: uptime
    name: "Uptime Sensor"
    id: uptime_sensor
    update_interval: 60s

text_sensor:
  - platform: version
    hide_timestamp: true
    name: "ESPHome Version"
    entity_category: diagnostic
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      icon: mdi:wifi
      entity_category: diagnostic
    ssid:
      name: "Connected SSID"
      icon: mdi:wifi-strength-2
      entity_category: diagnostic
